name: Build INWOX

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt install
      run: sudo apt install bison flex libgmp-dev libmpfr-dev libmpc-dev texinfo grub-pc-bin xorriso mtools -y
    - name: install toolchain
      run: make install-toolchain 
    - name: checkout path
      run: echo $PATH && ls -l $HOME/inwox-toolchain/bin && ls -l $HOME
    - name: make
      run: export PATH="$HOME/inwox-toolchain/bin:$PATH" && make
